# Generated by Django 4.1.4 on 2023-01-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abteilungen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abteilungen',
            name='image',
            field=models.ImageField(default=' ', upload_to='', verbose_name='abteilungen/'),
            preserve_default=False,
        ),
    ]
